# General Jekyll Config
highlighter: rouge
url: http://spraza.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
markdown: kramdown
excerpt_separator: <!--more-->
paginate: 10
paginate_path: "blog/page:num"
show_drafts: false
